### ISSUE TITLE
Unable to start docker image (and solution)

### ISSUE THREAD

**Issue by lucavix** [pgvector/pgvector#197]
If I build the image as it is the DB can't start:
```
# docker build --build-arg PG_MAJOR=15 -t pgvector .
... OMISSIS ...
# docker run -e POSTGRES_PASSWORD=password pgvector
initdb: error: invalid locale settings; check LANG and LC_* environment variables
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
```
and exit.

To make it working I've added the following lines to docker file:
```
RUN echo "en_US.UTF-8 UTF-8"> /etc/locale.gen 
RUN locale-gen
```

Thank you for your work.

**Comment by ankane** [comment]
Hi @lucavix, thanks for reporting! Looks like it's due to the `locales` package being updated (related: https://github.com/docker-library/postgres/issues/1112).

Two other solutions are:

1. Run `localedef` like the [`postgres` image](https://github.com/docker-library/postgres/blob/cba2a05c03706daf5f9a66b93a447540b62df063/15/bookworm/Dockerfile#L58)
2. Run `apt-mark hold locales`

Let me think about the best approach.
