### ISSUE TITLE
:bug: ORDER BY excluding results

### ISSUE THREAD

**Issue by jordanparker6** [pgvector/pgvector#203]
I have a query like below.

```
SELECT
    "Document".id,
    ("Document".embedding <#> $1) AS distance,
    "Document".embedding
FROM "Document"
WHERE "Document".metadata ->> 'country' = $2
ORDER BY "Document".embedding <#> $1
LIMIT 100
```

When i remove the `ORDER BY` I have 100 rows returned. 

With the `ORDER BY` zero rows are returned... Why is the ORDER BY excluding results?

**Comment by jkatz** [comment]
@jordanparker6 Can you provide more information about your setup:

1. How large is your dataset?
2. What command did you use to build the index?
3. What is the output of `EXPLAIN ANALYZE` on the query?
4. What is the value of `ivfflat.probes`? (i.e. `SHOW ivfflat.probes;`)
5. Does this occur for every query you're returning?

My "hunch" is that `ivfflat.probes` is `1`, and you're not seeing enough rows where `"Document".metadata ->> 'country' = $2`, so you'd likely need to increase `ivfflat.probes` on the query.

**Comment by jordanparker6** [comment]
> @jordanparker6 Can you provide more information about your setup:
> 
> 1. How large is your dataset?
> 2. What command did you use to build the index?
> 3. What is the output of `EXPLAIN ANALYZE` on the query?
> 4. What is the value of `ivfflat.probes`? (i.e. `SHOW ivfflat.probes;`)
> 5. Does this occur for every query you're returning?
> 
> My "hunch" is that `ivfflat.probes` is `1`, and you're not seeing enough rows where `"Document".metadata ->> 'country' = $2`, so you'd likely need to increase `ivfflat.probes` on the query.

1. I have table 4.5m rows of vectors
2. I built the index with the command below:
```
SET maintenance_work_mem = '1400MB';
DROP INDEX IF EXISTS document_ann_index;
CREATE INDEX document_ann_index ON "Document" 
USING ivfflat (embedding vector_ip_ops) WITH (lists = 2000);
```
3.  output of `EXPLAIN ANALYZE`:

```
,QUERY PLAN
0,Limit  (cost=5386.10..5426.95 rows=100 width=131) (actual time=11.745..16.527 rows=2 loops=1)
1,"  ->  Index Scan using document_ann_index on ""Document""  (cost=5386.10..14155.27 rows=21464 width=131) (actual time=11.743..16.524 rows=2 loops=1)"
2,"        Order By: (embedding <#> '[<embedding>]'::vector)"
3,        Filter: ((metadata ->> 'country'::text) = 'australia'::text)
4,        Rows Removed by Filter: 5637
5,Planning Time: 0.366 ms
6,Execution Time: 16.585 ms
```

4.  I have ran the above but received an error. `ERROR:  unrecognized configuration parameter "ivfflat.probes"`

5.  I will have to investigate more. I will also test by setting higher probes on the erroring case and see if it resolves.

**Comment by jkatz** [comment]
@jordanparker6 Thanks!

I'm more confident in my hunch -- you're only executing one probe by default, and within that list there do not seem to be any matches for the text you're looking for. Setting `ivfflat.probes` to a higher value will increase the probability that you see results.

The reason the non-index cases is giving you results is due to using "exact nearest neighbor", i.e. you're scanning the whole table, whereas in the above, without adjusting `ivfflat.probes`, you're only seeing 5637 rows, none of which seem to have the text in question.

**Comment by jordanparker6** [comment]
@jkatz setting `ivfflat.probes` to 10 saw the correct vectors returned.

Thanks for the help. I will play around with the `ivfflat.probes` in future before I raise any issues.

Would I be correct in assuming the WHERE is a post filter (i.e. it is being applied after the dot product results)? 

Are pre metadata filters possible with pgvector? Thinking more in the context of other vector databases like qdrant.

**Comment by jkatz** [comment]
@jordanparker6 

> Would I be correct in assuming the WHERE is a post filter (i.e. it is being applied after the dot product results)?

This does look like a "post" filter, i.e. the rows are eliminated by the "WHERE" clause after the ORDER. However, one could argue that its also "pre" filtering, given PostgreSQL is already looking over a reduced set of the overall data stored in the table, though I know "pre" filtering refers to a different concept.

> Are pre metadata filters possible with pgvector? Thinking more in the context of other vector databases like qdrant.

"pre"/"post" filtering are dependent on the execution path that the PostgreSQL query planner determines is the best (ideally, the fastest). I know this concept is currently being popularized in the realm of vector data storage, but its concept has existed in PostgreSQL since effectively its beginnings.

**Comment by ankane** [comment]
Hi @jordanparker6, to do pre-filtering, you can either remove the approximate index, or index the metadata (with an index the planner prefers over the approximate index). For jsonb, you can do:

```sql
CREATE INDEX ON "Document" USING gin (metadata jsonb_path_ops);
```

and use the containment operator for querying (`WHERE metadata @> '{"country": "australia"}'`).

More info: https://www.postgresql.org/docs/current/datatype-json.html#JSON-INDEXING
