### ISSUE TITLE
Pgvector DocumentStore for Haystack?

### ISSUE THREAD

**Issue by TuanaCelik** [pgvector/pgvector#207]
Hi maintainers, I hope it's ok I've created an issue for this but I wanted to ask whether any of the pgvector maintainers would be interested in creating a DocumentStore integration for [Haystack](https://github.com/deepset-ai/haystack), our open-source framework to build LLM applications. 
We have support for weaviate, pinecone, opensearch, milvus and some more, and [Qdrant](https://haystack.deepset.ai/integrations/qdrant-document-store) created an external integration too. If you would be interested in creating such a document store, I know some of our community members would find it very useful.

**Comment by jkatz** [comment]
@TuanaCelik Would it be a matter of adding the the appropriate vector indexing syntax to the existing [sql document store](https://github.com/deepset-ai/haystack/blob/main/haystack/document_stores/sql.py) (given pgvector is a PostgreSQL extension), or are you imagining a separate one?

**Comment by TuanaCelik** [comment]
Hey @jkatz - I would see this as a separate `DocumentStore` that's hosted in its own repo that a user could install separately. But actually, we were discussing this with @masci and we were wondering the following:
Haystack is currently going through a major update. This will take time, but in the coming months we would release Haystack v2. One thing we've already started to do though is change the DocumentStore API. Massi is currently preparing an example repository of what a new document store in Haystack v2 would look like. Would you perhaps be interested in implementing one of the first integrated v2 document stores? We could send you the example repo as soon as it's ready for you to review it and see if this is interesting to you.

**Comment by masci** [comment]
To confirm, I would create a new Document Store from scratch, leveraging the new API, so that you can make the technical choices that make more sense to you. If you're up for suggestions, I would use regular Postgres for the [CRUD part](https://github.com/deepset-ai/haystack/blob/main/haystack/preview/document_stores/protocols.py#L17), using psycopg directly (no ORMs or additional layers) and leverage pgvector for the retriever (similar to what I did for [Chroma](https://github.com/masci/chroma-haystack/blob/main/src/chroma_haystack/retriever.py#L12).

We worked to make the operation as smooth as possible, currently what you can do:
- Create a new repository that will host the project, I prepared a template that provides the basic Python scaffolding, along with packaging and testing: https://github.com/deepset-ai/document-store
- There is a Chroma Document Store that was built exactly like this, in case you need some inspiration: https://github.com/masci/chroma-haystack/tree/main

I will be happy to assist should you need any help!

**Comment by ankane** [comment]
Hi @TuanaCelik and @masci, thanks for sharing. It's not something I'd like to create / maintain as part of the pgvector org, but it'd be great if someone in the community wants to.

**Comment by cabljac** [comment]
Hey, I might be interested in taking this on, if no-one else has. I've used pg-vector before but am quite new with haystack, looks like a cool project.

**Comment by TuanaCelik** [comment]
Hey @cabljac that would be awesome! We're actually working on a major upgrade for Haystack (Haystack 2.0) and if you're up for it, a Document Store for Haystack 2.0 would be awesome. Feel free to contribute here: https://github.com/deepset-ai/haystack-core-integrations/tree/main

@masci sound good?

**Comment by cabljac** [comment]
@TuanaCelik should i still build off of the template mentioned above?

**Comment by schacki** [comment]
Any news here?

**Comment by TuanaCelik** [comment]
I'm so sorry @shacki that your comments went under the radar, seems my notification settings were wrong. We have a community contributor working on a PR to integrate now but it's still a WIP: https://github.com/deepset-ai/haystack-core-integrations/pull/172

You could check that out.
