### ISSUE TITLE
Clarification about accuracy of partially indexed dataset

### ISSUE THREAD

**Issue by levchik** [pgvector/pgvector#21]
Hi, thanks for this wonderful extension, great work!

So, as far as I understand, users are supposed to create index on vector column after data has been inserted. I do have the need to regularly insert, update & delete vectors in that column. I set up periodic job that on some timer does REINDEX CONCURRENTLY to keep search queries fast.

The question is, I might run into scenario when, firstly, 100% percent of the data has been indexed, then 50% of that data is removed and then 50% of new data is added BEFORE reindex happens. It would mean 50% indexed data and 50% non-indexed data. How does the algorithm works in this situation?

**Comment by ankane** [comment]
Hey @levchik, reindexing is only needed if the distribution of data changes significantly. If the new vectors are similar to the original/deleted vectors, you don't need to reindex (new data is indexed when it's inserted).

**Comment by levchik** [comment]
Thanks for your fast response, @ankane 

I wonder, what do you mean by "data changes significantly"? And how "similar" vectors should be to not require reindexing?

**Comment by ankane** [comment]
Internally, an IVFFlat index divides the data into multiple lists. It uses k-means clustering to determine the center of the clusters when the index is created. For instance, if we have the following 4 vectors and 2 lists, we'll end up with:

- List 1 - center: `[1.5, 1.5]`, vectors: `[1, 1]`, `[2, 2]`
- List 2 - center: `[3.5, 3.5]`, vectors: `[3, 3]`, `[4, 4]`

Ideally, the vectors are distributed roughly evenly between lists. However, if all new vectors go to a single list (for instance, all new vectors have elements > 3), that list will have many more vectors and take longer to search than the other lists. In this instance, reindexing will generate new centers that distribute the data evenly.

This is a simplified example, but that's what's meant by "the distribution of data changes significantly". Does that make sense?

From a practical perspective, if you create the index when the table is empty, you should reindex once the table has some data (otherwise, the centers are random). Otherwise, I'd expect most users should never need to reindex.

**Comment by levchik** [comment]
That's interesting, thanks such detailed answer! So I guess reindexing better be happening when I realize that most (>80-90%?) of my data has been updated since last index/reindex, instead of just reindexing periodically.

**Comment by ankane** [comment]
In many cases, you shouldn't need to reindex even when all of the data changes, but you can always experiment to see how it affects your specific application.

**Comment by levchik** [comment]
Ok, thanks for the insight. Closing this issue now.

**Comment by louis030195** [comment]
Thanks for the explanation!

Can you confirm this:

![image](https://github.com/pgvector/pgvector/assets/25003283/53061111-230f-4ed2-919a-f729dee38506)

Let's say I just ran `index vectors ...` and suddenly add a ton of vectors related to 'my observations of ant houses and behaviours' which I guess has a distribution far from existing vectors, it means I should likely reindex to make search on this 'cluster' faster?
