### ISSUE TITLE
Vector normalization

### ISSUE THREAD

**Issue by ataudt** [pgvector/pgvector#220]
Hi, is there any way to normalize vectors? I want to normalize to unit length.

**Comment by ankane** [comment]
Hi @ataudt, there's not a function for this right now, but I've added support in the [normalize_l2 branch](https://github.com/pgvector/pgvector/compare/normalize_l2). Can you share more about the use case for having this in the database vs normalizing beforehand?

**Comment by ataudt** [comment]
Thanks, the normalize_l2 function seems to work as expected.

**Comment by jkatz** [comment]
FWIW, I've been typically writing my own normalization functions as part of testing, so this will save a lot of time when moving between databases during tests. Though again, for my purposes, it's testing 😄

**Comment by nikololay** [comment]
hey everyone, just for my understanding

to compute any distance other than `l2_distance` I ought to normalize my vectors prior?

**Comment by kevin19930919** [comment]
> hey everyone, just for my understanding
> 
> to compute any distance other than `l2_distance` I ought to normalize my vectors prior?

As i know `cosine distance` only cares the orientation, it should normalize with the magnitude?

**Comment by kevin19930919** [comment]
> > hey everyone, just for my understanding
> > to compute any distance other than `l2_distance` I ought to normalize my vectors prior?
> 
> As i know `cosine distance` only cares the orientation, it should normalize with the magnitude?

sorry, I misunderstand the term with `cosine distance` and `cosine similarity`.
u should normalize it by yourself.

**Comment by ankane** [comment]
Quick update: there's a good chance this function will be needed to make indexes work with more data types, so it may be included in 0.6.0.

**Comment by ViktorQvarfordt** [comment]
Can one specify to use dot product distance instead of cosine distance? Assuming the vectors are already normalized one does not have to divide by the norm of the two vectors. This should significantly improve computational performance.

**Comment by ViktorQvarfordt** [comment]
Answering my own question: This is covered by using the `<#>` operator.

From the README:

>If vectors are normalized to length 1 (like OpenAI embeddings), use inner product for best performance.
>
> `SELECT * FROM items ORDER BY embedding <#> '[3,1,2]' LIMIT 5;`
>
> Note: <#> returns the negative inner product since Postgres only supports ASC order index scans on operators.

I'll write out more context:

Let `u` and `v` be vectors, and let `θ` be the angle between the vectors. We have these definitions and relations:

* |u| = √( ∑ₖ uₖ² ) = `u.map(x => x**2).sum().sqrt()`
* <u, v> = ∑ₖ uₖvₖ = `zip(u, v).map([x, y] => x * y).sum()`
* <u, v> = cos(θ) |u| |v|
* cos(θ) = <u, v> / ( |u| |v| ) = ∑ₖ uₖvₖ / ( √( ∑ₖ uₖ² ) √( ∑ₖ vₖ² ) )
* |u|² = <u, u>
* u is normalized if |u| = 1

Term definitions:
* cosine_similarity(u, v) = cos(θ)
* dist_cos = 1 - cosine_similarity(u, v) = 1 - cos(θ)
* dist_l2(u, v) = |u - v|

These are exposed as operators in Postgres, but the operators are "the negative counterparts", so they can be used for index scans. Postgres only supports ASC order index scans.

| Operator | Description | Definition |
|--------|--------|--------|
| <=> | Cosine distance/"1 minus cosine similarity" |dist_cos(u, v) = 1-cos(θ) = -<u, v> / ( \|u\| \|v\| ) = <br /> -∑ₖ uₖvₖ / ( √( ∑ₖ uₖ² ) √( ∑ₖ vₖ² ) ) | 
| <#> | Negative inner product/dot product/scalar product | -<u, v> = -∑ₖ uₖvₖ |
| <-> | Euclidian distance/L2 distance | dist_L2(u, v) = \|u - v\| = √( ∑ₖ (uₖ - vₖ)² ) |

Observe how cheap it is to compute the inner product <u, v> compared to the cosine similarity cos(θ) = <u, v> / ( |u| |v| ). Dividing by the norm of u and v adds a lot of computational complexity.

If u and v are normalized (that is, |u| = |v| = 1) we have that dist_cos(u, v) = 1 - <u, v>. Meaning that the cosine distance can be computed using only the inner product. **Therefore, it is preferred to work with normalized vectors and compute distance using the inner product.**

Furthermore, if u and v are normalized, then the cosine distance gives an equivalent ordering as the L2 distance. To see this:

* dist_cos(u, v) = 1 - cos(θ) = 1 - <u, v> / ( |u| |v| ) = 1 - <u, v>
* dist_l2(u, v)² = |u - v|² = ∑ₖ (uₖ - vₖ)² = ∑ₖ ( uₖ² + vₖ² - 2uₖvₖ ) = |u|² + |v|² - 2<u,v> = 2 - 2<u, v>

That is, dist_l2(u, v)² = 2 dist_cos(u, v). This implies that the cosine distance and the L2 distance give the same ordering for pairs of normalized vectors.

This is relevant since when we do vector search, we compare vectors pairwise to find the most similar vectors. Let u represent the query vector, and let v represent the document vector. We search for the vectors v with the smallest cosine distance dist_cos(u, v). We can create an ordering of pairs of vectors (u1, v2) <₁ (u2, v2) defined by dist_cos(u1, v1) < dist_cos(u2, v2). And similarly, an ordering (u1, v2) <₂ (u2, v2) defined by dist_l2(u1, v1) < dist_l2(u2, v2). These two orderings, <₁ and <₂, are equivalent since dist_l2(u1, v1) < dist_l2(u2, v2) ⟺ dist_l2(u1, v1)² < dist_l2(u2, v2)² ⟺ 2 dist_cos(u1, v1) < 2 dist_cos(u2, v2). This holds since both sides of the inequality are positive, and the square of a positive number is strictly increasing.

**Comment by ankane** [comment]
Added an `l2_normalize` function in the commit above (for both `vector` and `halfvec`), which will be included in 0.7.0 (#508). Thanks for the suggestion @ataudt.
