### ISSUE TITLE
Supabase PosgtreSQL vector column issues

### ISSUE THREAD

**Issue by ma1nojk** [pgvector/pgvector#226]
Hello Team,

I just noticed that when I create a column in supabase posgresql table with the column type "vector"  the vector value of the embedding after the decimal gets truncated to 10 digits while the original embedding value is 19 digits .
Am i doing something wrong while creating the column or is it by design ? , also does it have any impact on the accuracy of the results while using the similarity SQL queries on these vector columns.
Thanks in advance.

**Comment by jkatz** [comment]
This sounds like the original vector you're using is an 8-byte float (`double`), whereas the internal storage for pgvector uses a 4-byte float (`float`).

For "result accuracy", it depends on many factors, particularly on if significant differentiating information is held in the lower values. Because you're reducing the precision of each value, this will impact recall in some way, but it may not even be noticeable depending on your data set.

**Comment by ma1nojk** [comment]
Thx jkatz for your response :) , is there a way to increase the vector column byte size to 8 bytes in supabase or is this a limitation ?

**Comment by jkatz** [comment]
@ma1nojk  This 4-byte size is directly tied to the `vector` type provided by pgvector. You would need to directly modify the data type to support the increase in size and run a custom version of pgvector. Unless there's a reason you really need 8-bytes, I'd recommend against it as it will impact both performance and the amount of data you need to store on disk.

**Comment by ankane** [comment]
Hi @ma1nojk, another thing you can do to keep the original precision (for storage) is store the data as `float8[]` or `numeric[]` and then index / query them as (lower precision) vectors: https://github.com/pgvector/pgvector/issues/182#issuecomment-1631245906
