### ISSUE TITLE
Enable ivfflat to support more than 2000 dims when BLCKSZ is bigger than 8kB

### ISSUE THREAD

**Issue by fanfuxiaoran** [pgvector/pgvector#248]
Hi,  in my local postgres, the BLCKSZ is 32kB, I thought the ivfflat index could support more than 2000 dims vector with that, but failed. Because ivfflat uses 'IndexTupleData' which can only support as much as 8kB length of data to fit in the tuple.  

I made a patch to enable the ivfflat to support more dims when the BLCKSZ is bigger. But in the patch, I replace IndexTupleData with IvfflatTupleData, which is a big deal.  Modifying the index tuple format will lead to upgrading issues. 

I'm not sure if it is a good idea to do this, so just post an issue here to discuss about it
[0001-Enable-ivfflat-to-support-more-than-2000-dims-when-B.patch](https://github.com/pgvector/pgvector/files/12484987/0001-Enable-ivfflat-to-support-more-than-2000-dims-when-B.patch)

**Comment by pashkinelfe** [comment]
I'm not sure it's very often scenario to use bigger BLKSZ for accommodating bigger dimensioned vectors on plain storage. But it's useful way of performance tuning.
Provided the patch for this is not complicated, I'd suggest converting it to PR for further review.

**Comment by pashkinelfe** [comment]
The question is, now pgvector doesn't explicitly use t_info field that limits the size of the index tuple to be represented by 0-12 bits. But we have t_info field as a part of IndexTuple. This allows us to store "has nulls" and "has var-width" flags. Do we want to drop this at all?

This will make ivfflat indexes built in 0.5.0- to be incompatible with upgrades to next version.

**Comment by jkatz** [comment]
@fanfuxiaoran Thanks for the proposal! It's great to discuss things like this.

>  Modifying the index tuple format will lead to upgrading issues.

To me this is a hard stop, at least as of the moment. The current thinking on allowing for more dimensions to be indexed is to use [product quantization][1] because 1/ it's been shown to significantly reduce the amount of storage required to store a vector and 2/ it can be applied within the default 8KB limit, as most PostgreSQL installations do not modify the page size, and 3/ while not yet POC'd, I think we can do PQ without modifying the on-disk format on existing indexes.

My vote would be to first see how far we can push vector storage with product quantization.

Thanks!

[1]: https://github.com/pgvector/pgvector/issues/27

**Comment by fanfuxiaoran** [comment]
> The question is, now pgvector doesn't explicitly use t_info field that limits the size of the index tuple to be represented by 0-12 bits. Still we have t_info field as a part of IndexTuple. This allows us to store "has nulls" and "has var-width" flags. Do we want to drop this at all?

ivfflat only supports one column as `amcanmulticol` is set to false. So "has nulls" as "has var-width" are not neccssary to it.
> 
> This will make ivfflat indexes built in 0.5.0- to be incompatible with upgrades to next version.

Exactly, that's the thing I worried about

**Comment by ankane** [comment]
Hi @fanfuxiaoran, thanks for sharing.

Any backwards-incompatible changes to the on-disk format will need to involve incrementing the index version and updating the code to support both the old and new versions. This will add a lot of complexity to the code/testing, which I don't think is justified by the benefit in this situation.

(also, please use PRs for proposed patches as previously so people can view them without downloading files)
