### ISSUE TITLE
Performance questions

### ISSUE THREAD

**Issue by bediu** [pgvector/pgvector#310]
Hey there, thank you for the amazing thing you've built!

I need to know about performance. I'm thinking of adding this to my production database, but now I need to consider hardware requirements for pgvector as well.

Here are some questions I need answers to:

* Is there a minimum hardware requirement for pgvector?
* Does everything need to run in RAM?

Here's a more specific question:
* What sort of hardware would I need if I were to store a 5GB pdf file, split into chunks of course, and constantly perform 1-2 similarity searches per second?
* What do I need to upgrade to make search results faster?
 
Thank you for your help!

**Comment by jcrupi** [comment]
That's a great question. I too would like benchmarks if you have them

**Comment by jkatz** [comment]
This is a complicated topic that's challenging to reduce down to a few sentences. There are many things to consider when trying to evaluate what infrastructure makes for running your vector workloads, which include:

* How important is accuracy to your workload (do you need 100% recall or is an approximation good enough?)
* How many dimensions are your vectors?
* How many vectors are you storing?
* What level of concurrency are you trying to support?
* What other workloads are in your database at the same time? What are the access patterns for those?

Understanding those can help with capacity planning. To try to give some directional answers to your questions:

> Is there a minimum hardware requirement for pgvector?

This would be the same as the minimum hardware requirement for PostgreSQL.

> Does everything need to run in RAM?

This depends on what level of performance you're trying to achieve. One benefit of HNSW indexing is that searches tend to occur over a smaller space, and while you may be needing to access fewer pages (the fundamental storage unit of PostgreSQL), if the pages are not in memory you will still have to go to disk to fetch them.

So no, you don't need to keep everything in RAM, but that's part of the performance tradeoff.

> What sort of hardware would I need if I were to store a 5GB pdf file, split into chunks of course, and constantly perform 1-2 similarity searches per second?

This depends on the LLM or other AI/ML model that  you're using. How many vectors does it create? What is the dimensionality of the vectors? Are you storing additional content in the table? In the database?

1-2 similarity searches / second is not much -- based on the overall size of the data set you may even be able to handle that without any indexing. However, without more information it's hard to make any kind of recommendations.

> What do I need to upgrade to make search results faster?

There are many toggles to accelerate search results. Algorithmic, you can reduce parameters such as `hnsw.ef_search` or `ivfflat.probes` to lower numbers, which provides a less exhaustive search at the tradeoff of recall. However, that's the easiest way to speed up the search.

When it comes to adjusting hardware, again, it depends on your workload characteristics. If you're becoming CPU bound, either due to increased concurrency or calculations over high dimensionality vectors, you may need to increase CPU. If your workload is no longer fitting into memory, you can increase RAM. If you're seeing I/O bottlenecks, you may need a faster storage layer. These are all generic guidelines, because it really depends on what you're seeing with your workload.

Before the 0.5.0 release of the HNSW implementation in pgvector, I wrote a blog post that [outlined several methods to determine performance characteristics of vector workloads](https://jkatz05.com/post/postgres/pgvector-hnsw-performance/). This was evaluating peak performance under one connection, and production workloads may have higher concurrency. It does point out different areas you need to consider when evaluating performance of vector search, which could be helpful to your performance evaluations.

**Comment by chuyqa** [comment]
The requirements have been much smaller than I was expecting. 

For 1M rows of network logs, loaded into a 1.1GB table I was seeing my memory usage be 50-100MB and retrieving data in ~100ms on a ryzen 3900X. 

Section 3 does the actual querying:
https://gist.github.com/chuyqa/e122155055c1e74fbdc0a47f0d5e9c72

**Comment by bediu** [comment]
Thank you, that's an amazing answer! @jcrupi For reference, I will be using OpenAI's embedding model which uses 1536 dimensions.

**Comment by ankane** [comment]
Thanks @jkatz!
