### ISSUE TITLE
How often if at all re-indexing needs to be done?

### ISSUE THREAD

**Issue by mgoldenbe** [pgvector/pgvector#335]
There is a very favorable (for `pgvector`) comparison with Pinecone [here](https://supabase.com/blog/pgvector-vs-pinecone).
However, one thing they did not mention is that the Pinecone algorithm claims to scale more gracefully than HNSW. Here is a quote from [the article](https://www.pinecone.io/blog/hnsw-not-enough/) in the Pinecone blog:

> HNSW was designed for relatively static datasets, though, and production applications are anything but static. As your data changes, so do the vector embeddings that represent your data, and, consequently, so must the vector index. When you make frequent changes to a bolted-on HNSW index, its memory consumption begins to grow… a lot.
> To deal with the growing memory consumption, you would have to do some or all of following:
>     - Tolerate increasingly higher query latencies, up until timeouts.
>     - Pay high sums of money to avoid those high query latencies.
>     - Frequently adjust the HNSW index parameters to maintain query latency despite less available memory, if you have access and expertise to do so.
>     - Frequently rebuild the index, and either tolerate downtime during the rebuild process or manage a [blue-green deployment](https://www.redhat.com/en/topics/devops/what-is-blue-green-deployment) each time.

Is what's being said here correct? If so, how does `pgvector` go about the last item? Does it rebuild the index (either actively or lazily)? Should I rebuild the index once in a while? If so, how often?

**Comment by jkatz** [comment]
I've been doing a lot of testing of HNSW on very large data sets (millions on up), and while it does take more time to insert a vector in an index that has hundreds of millions of vectors, thus far I have not seen any pressing need to re-index. However, I'd qualify that statement as this has been on either known test data sets or simulated vector data.

The HNSW implementation in pgvector also supports updates and deletes, so if you have a record that changes, it will be appropriately reindexed and cleaned up, so you don't have to rebuild it due to that reason.

**Comment by ankane** [comment]
To add to @jkatz's answer: the graph is repairing during vacuuming, so no need to reindex.

**Comment by JadenGeller** [comment]
The [FreshDiskANN paper](https://arxiv.org/pdf/2105.09613.pdf) proposes 2 deletion policies for HNSW and determine both are ineffective. I'm wondering if pgvector graph repair uses a different technique that is shown to provide greater recall? Thank you!

**Comment by ankane** [comment]
Hi @JadenGeller, pgvector doesn't use either of those deletion policies. On vacuum, it updates connections for each live element by seeing what the connections would be if the element was freshly inserted. Check out [hnswvacuum.c](https://github.com/pgvector/pgvector/blob/master/src/hnswvacuum.c) for the full approach.

**Comment by wahajali** [comment]
@ankane @jkatz I modified [VectorDBBench](https://github.com/zilliztech/VectorDBBench) to calculate the recall by deleting and reinserting 10% of the dataset (randomly selected) for OpenAI 500K data on an HNSW index with default values for m, ef_search and ef_construction. I repeated this cycle 20 times, and more or less the recall stayed constant around 0.947. Currently, I don't manually trigger vacuum. 
I wanted to ask if this is something to be expect?

**Comment by olad32** [comment]
@ankane @jkatz what do you think of this azure team blog post ? https://techcommunity.microsoft.com/blog/adforpostgresql/introducing-diskann-vector-index-in-azure-database-for-postgresql/4261192
They introduced a new (closed source) extension using DiskANN, claiming that it overcomes pgvector limitations with filtered query (i assume this is no longer an issue since pgvector 0.8.0) and about a decreased recall after many Insertions, Deletions, and Modifications, are they mislead ?
Is the benchmark made by @wahajali a good proof that their blog statement are wrong ?
