### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by ankane** [pgvector/pgvector#38]
Continuation of #37

@cdtaichen Re https://github.com/pgvector/pgvector/issues/37#issuecomment-1270980094, for GCC, I think the commands will probably be similar to Linux, which is:

```sh
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -march=native -ftree-vectorize -fassociative-math -fno-signed-zeros -fno-trapping-math -fPIC -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/ivfbuild.o src/ivfbuild.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -march=native -ftree-vectorize -fassociative-math -fno-signed-zeros -fno-trapping-math -fPIC -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/ivfflat.o src/ivfflat.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -march=native -ftree-vectorize -fassociative-math -fno-signed-zeros -fno-trapping-math -fPIC -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/ivfinsert.o src/ivfinsert.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -march=native -ftree-vectorize -fassociative-math -fno-signed-zeros -fno-trapping-math -fPIC -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/ivfkmeans.o src/ivfkmeans.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -march=native -ftree-vectorize -fassociative-math -fno-signed-zeros -fno-trapping-math -fPIC -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/ivfscan.o src/ivfscan.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -march=native -ftree-vectorize -fassociative-math -fno-signed-zeros -fno-trapping-math -fPIC -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/ivfutils.o src/ivfutils.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -march=native -ftree-vectorize -fassociative-math -fno-signed-zeros -fno-trapping-math -fPIC -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/ivfvacuum.o src/ivfvacuum.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -march=native -ftree-vectorize -fassociative-math -fno-signed-zeros -fno-trapping-math -fPIC -I. -I./ -I/usr/include/postgresql/14/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/vector.o src/vector.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -march=native -ftree-vectorize -fassociative-math -fno-signed-zeros -fno-trapping-math -fPIC -shared -o vector.so src/ivfbuild.o src/ivfflat.o src/ivfinsert.o src/ivfkmeans.o src/ivfscan.o src/ivfutils.o src/ivfvacuum.o src/vector.o -L/usr/lib/x86_64-linux-gnu  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-10/lib  -Wl,--as-needed 
```

Also, outstanding questions from #37:

1. What does the Postgres server log say about the crashes?
2. Does the `windows` branch work for MSVC?

**Comment by cdtaichen** [comment]
Hi Kane,

This is the error log using vector.dll compiled by MSVC, it looks like there has invalid address access error.

2022-10-07 06:49:22.994 MDT [17084] LOG:  starting PostgreSQL 14.5, compiled by Visual C++ build 1914, 64-bit
2022-10-07 06:49:22.996 MDT [17084] LOG:  listening on IPv6 address "::", port 5433
2022-10-07 06:49:22.996 MDT [17084] LOG:  listening on IPv4 address "0.0.0.0", port 5433
2022-10-07 06:49:23.107 MDT [5900] LOG:  database system was shut down at 2022-10-07 06:49:21 MDT
2022-10-07 06:49:23.156 MDT [17084] LOG:  database system is ready to accept connections
2022-10-07 07:07:28.921 MDT [17084] LOG:  server process (PID 17264) was terminated by exception 0xC0000005
2022-10-07 07:07:28.921 MDT [17084] DETAIL:  Failed process was running: CREATE INDEX ON items USING ivfflat (embedding vector_ip_ops);
2022-10-07 07:07:28.921 MDT [17084] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2022-10-07 07:07:28.921 MDT [17084] LOG:  terminating any other active server processes
2022-10-07 07:07:28.951 MDT [17084] LOG:  all server processes terminated; reinitializing
2022-10-07 07:07:29.073 MDT [12440] LOG:  database system was interrupted; last known up at 2022-10-07 06:54:24 MDT
2022-10-07 07:07:29.638 MDT [12440] LOG:  database system was not properly shut down; automatic recovery in progress
2022-10-07 07:07:29.645 MDT [12440] LOG:  redo starts at 0/103C69F0
2022-10-07 07:07:29.645 MDT [12440] LOG:  invalid record length at 0/103C6AD8: wanted 24, got 0
2022-10-07 07:07:29.645 MDT [12440] LOG:  redo done at 0/103C6AA0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2022-10-07 07:07:29.739 MDT [17084] LOG:  database system is ready to accept connections
2022-10-07 07:07:30.382 MDT [17084] LOG:  server process (PID 2776) was terminated by exception 0xC0000005
2022-10-07 07:07:30.382 MDT [17084] DETAIL:  Failed process was running: CREATE INDEX ON items USING ivfflat (embedding vector_ip_ops);
2022-10-07 07:07:30.382 MDT [17084] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2022-10-07 07:07:30.382 MDT [17084] LOG:  terminating any other active server processes
2022-10-07 07:07:30.413 MDT [17084] LOG:  all server processes terminated; reinitializing
2022-10-07 07:07:30.520 MDT [15564] LOG:  database system was interrupted; last known up at 2022-10-07 07:07:29 MDT
2022-10-07 07:07:30.901 MDT [15564] LOG:  database system was not properly shut down; automatic recovery in progress
2022-10-07 07:07:30.907 MDT [15564] LOG:  invalid record length at 0/103C6B50: wanted 24, got 0
2022-10-07 07:07:30.907 MDT [15564] LOG:  redo is not required
2022-10-07 07:07:30.969 MDT [17084] LOG:  database system is ready to accept connections


MSVC is not very good at support C99, so I don't know this problem was caused by the complier or not.
I have to change source code to "Vector *items;" so that can pass the MSVC compile, but I think this change is no problem.

typedef struct VectorArrayData
{
	int			length;
	int			maxlen;
	int			dim;
#ifdef _MSC_VER
	Vector		*items;
#else
	Vector		items[FLEXIBLE_ARRAY_MEMBER];
#endif
}			VectorArrayData;

//---------

For your windows branch, I know you add DLLEXPORT to each functions, but I did this already or can not load the vector.dll to use, so this change is no effect the result.

//---------

For GCC compiling, I am following your script to create a new vector.dll, when try to load this extension, "The specified module could not be found" displayed. I am not familar with GCC so I can not provide more info this time.
Attachment is compile batch file and output vector.dll.

[vector-dll.zip](https://github.com/pgvector/pgvector/files/9734315/vector-dll.zip)

**Comment by ankane** [comment]
Thanks for the logs. It looks like `0xC0000005` is a [memory access issue](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55).

I think the change might be an issue. From [this comment](https://github.com/postgres/postgres/blob/278273ccbad27a8834dfdf11895da9cd91de4114/src/include/c.h#L342-L350) in the Postgres code, it sounds like MSVC should support `FLEXIBLE_ARRAY_MEMBER`. What error are you seeing without the change?

**Comment by cdtaichen** [comment]
MSVC could not compile if you keep using FLEXIBLE_ARRAY_MEMBER in VectorArrayData, because there is another FLEXIBLE_ARRAY_MEMBER in the Vector.

Do you have a cross compiled vector.dll(0.2.7) for Windows OS? I can put it in my environment to see what will happen.

**Comment by ankane** [comment]
I'm not really sure what the first part means. And no, I haven't cross-compiled it.

I don't think I can spend more time on this right now, but hopefully someone can figure it out in the future and share.

**Comment by ankane** [comment]
Experimental support for Windows is now available with `nmake`:

```sh
nmake /F Makefile.win
nmake /F Makefile.win install
```

**Comment by mrerhuo** [comment]
![image](https://github.com/pgvector/pgvector/assets/9547741/1451ad55-8b2d-4b62-8816-ce66cc89018c)
How to solve?

**Comment by mrerhuo** [comment]
Makefile.win(28) : fatal error U1050: PGROOT is not set
Stop.

**Comment by ankane** [comment]
Hi @mrerhuo, see the [instructions for Windows](https://github.com/pgvector/pgvector#windows) for how to set `PGROOT`.
