### ISSUE TITLE
Vacuums extremely slow for HNSW indices?

### ISSUE THREAD

**Issue by williamhakim10** [pgvector/pgvector#450]
We recently deleted a large part of a ~20 million row table (with an HNSW index size of ~31GB). Attempting to manually vacuum the table took us 10 hours (before we cancelled it) - vacuum got stuck on vacuuming the HNSW index. We tried doing a parallel vacuum and that also didn't seem to help. Our metrics showed that we weren't limited by CPU or memory at any point. Eventually we gave up, dropped the index, vacuumed the table (took <10 mins to complete), and recreated the index. Any guidance as to what we were doing wrong and/or should be doing better in future?

**Comment by ankane** [comment]
Hi @williamhakim10, `autovacuum_vacuum_cost_limit` and `autovacuum_vacuum_cost_delay` control the vacuum speed ([docs](https://www.postgresql.org/docs/current/runtime-config-autovacuum.html)). You can set these higher on individual tables if needed.

Parallel vacuum isn't currently supported, but would be nice to add at some point (added to #27).

**Comment by jkatz** [comment]
@williamhakim10 Curious -- do you frequently updated rows and/or vectors in the table where vacuum was stuck?

**Comment by williamhakim10** [comment]
> Hi @williamhakim10, `autovacuum_vacuum_cost_limit` and `autovacuum_vacuum_cost_delay` control the vacuum speed ([docs](https://www.postgresql.org/docs/current/runtime-config-autovacuum.html)). You can set these on individual tables if needed.
> 
> Parallel vacuum isn't currently supported, but would be nice to add at some point (added to #27).

It feels like this shouldn't matter because I'm manually triggering the vacuum? Unless I misunderstand what these settings do.

@jkatz there would have been only an extremely small number of writes to that table while vacuum was happening, and no updates or deletes as far as I know.

**Comment by ankane** [comment]
My bad, thought you were talking about autovacuum for some reason.

Vacuum should max out a single CPU. Is that what you're seeing?

In general, vacuuming will be slower than building the index, since the index build can happen in-memory and then write to disk, while vacuuming needs to persist changes to disk for every tuple (which for live tuples, requires updating many pages).

**Comment by ankane** [comment]
Also, just looked into parallel vacuuming, and it looks like it only supports a single worker per index (so won't really help here).

**Comment by williamhakim10** [comment]
I don't believe Cloud SQL allows you to break out CPU utilization per-core, but generally yes we're seeing total CPU utilization consistent with one core being maxed out over the many hours we attempted to vacuum.

**Comment by ankane** [comment]
Unfortunately, the time to vacuum will likely be closer to the time to build the index with a very small value of `maintenance_work_mem` (where the build happens mostly on-disk instead of in-memory, which is significantly slower).

Going back to your original question, I'm not sure there's anything you can do to speed it up right now.

**Comment by williamhakim10** [comment]
OK cool, this is good to know. Perhaps this might merit a comment in the README; feels like other folks may unexpectedly encounter this because the size of the HNSW indices can get pretty large without *that* many vectors, such that large deletes may lead to a situation in which autovacuum can't complete (and even manual vacuum can't run in a reasonable amount of time) leading to unexpected drops in recall? Happy to propose something in a PR if you think it's valuable?

**Comment by ankane** [comment]
Spoke too soon. It looks like rebuilding the index with `REINDEX INDEX CONCURRENTLY` before vacuuming will make it much faster (since it can rebuild in-memory with `maintenance_work_mem` and parallel workers when available).

```sql
REINDEX INDEX CONCURRENTLY index_name;
VACUUM table_name;
```

Will add a note to the readme.

**Comment by williamhakim10** [comment]
Awesome. Appreciate you guys walking this through with me!

**Comment by hlinnaka** [comment]
We are pretty aggressive in the RepairGraph phase, to add replacement edges for the removed ones, to keep the index in good order. I'm not sure that's a good tradeoff. It would probably be better to more lazy. For example, only call HnswFindElementNeighbors if more than 10% of an element's neighbors have been deleted. Otherwise just remove the deleted neighbors and leave some empty slots in it.

**Comment by ankane** [comment]
It's an interesting idea. Would need to understand the impact on recall and vacuum speed to have a better idea of if it's (subjectively) worth the trade-off.
