### ISSUE TITLE
Mac M1/M2 arm Arch issue installation 

### ISSUE THREAD

**Issue by ideavision** [pgvector/pgvector#456]
I got this error when I wanted to install it on Mac M1:
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [vector.so] Error 1

**Comment by ankane** [comment]
Hi @ideavision, can you paste the commands you ran and their full output (with any personal info removed)?

**Comment by sourcesync** [comment]
> I got this error when I wanted to install it on Mac M1: clang: error: linker command failed with exit code 1 (use -v to see invocation) make: *** [vector.so] Error 1

Hey @ideavision ...I'm on M2.  It helped running "make VERBOSE=1" to get the individual build commands to locate failures.

**Comment by smithqualwebs** [comment]
Hey i am facing this and i struggled a lot with this in M!

i tried to run "make" command after cloning the master branch

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [vector.so] Error 1

**Comment by demipixel** [comment]
Ultimately my issue was that I had an x86 version of postgres installed because my brew was transferred over from my old mac to my M1 (surprised this hasn't caused any other issues to date).

Unfortunately had to go through the pain of uninstalling brew (along with all packages) and reinstalling brew so it would install the M1 version, but after installing postgres and making pgvector, had no issues.
