### ISSUE TITLE
Trouble on installing with mac (M1)

### ISSUE THREAD

**Issue by Lesley217** [pgvector/pgvector#515]
I have followed the methods for installation of pgvector. I changed the path for Postgres accordingly but I received the error message:
2024-04-10 10:08:58.179 GMT [53653] FATAL:  --pgxs requires a value
cp sql/vector.sql sql/vector--0.6.2.sql

Is there anything that I need to install to resolve the error ?

**Comment by ankane** [comment]
Hi @Lesley217, can you paste the commands you ran and their full output (with any personal info removed)? Also, how was Postgres installed?

**Comment by rhunold** [comment]
Hi also have an issue with a M1.
Is it the same issue that occur to [Lesley217](https://github.com/Lesley217) ? I don't know.

My postgres is 15.2
The make command say MacOSX11.1.sdk was not found (so unsucessfull to install). Try to uninstall and reinstall xcode but worse (old sdk not installed). Finally found a version of MacOSX11.1.sdk on a github account (https://github.com/phracker/MacOSX-SDKs).
But got still few error 
15/lib  -Wl,-dead_strip_dylibs   -bundle_loader /Library/PostgreSQL/15/bin/postgres
ld: warning: -multiply_defined is obsolete
ld: warning: search path '/opt/local/Current_v15/lib' not found
ld: warning: search path '/opt/local/20220418/lib' not found
ld: warning: search path '/opt/local/Current_v15/lib' not found
ld: warning: search path '/opt/local/Current_v15/lib' not found
ld: warning: -multiply_defined is obsolete
ld: warning: search path '/opt/local/Current_v15/lib' not found
ld: warning: search path '/opt/local/20220418/lib' not found
ld: warning: search path '/opt/local/Current_v15/lib' not found
ld: warning: search path '/opt/local/Current_v15/lib' not found

So indeed, can't finish the install with the command "make install". Here the message I get if I try :
(env) ➜  pgvector git:(v0.6.2) make install
/bin/sh /Library/PostgreSQL/15/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/Library/PostgreSQL/15/lib/postgresql'
/bin/sh /Library/PostgreSQL/15/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/Library/PostgreSQL/15/share/postgresql/extension'
/bin/sh /Library/PostgreSQL/15/lib/postgresql/pgxs/src/makefiles/../../config/install-sh -c -d '/Library/PostgreSQL/15/share/postgresql/extension'
/usr/bin/install -c -m 755  vector.so '/Library/PostgreSQL/15/lib/postgresql/vector.so'
install: /Library/PostgreSQL/15/lib/postgresql/vector.so: Permission denied
make: *** [install-lib-shared] Error 71

Finally, there is no file named pgvector in /Library/PostgreSQL/15/share/postgresql/extension.

Any clue or process to do ?
Wonder if I should upgrade to Postgresql 16 because I've read that their is more defaut extention by default.

**Comment by ankane** [comment]
@rhunold Please create a separate issue for this, and include all of the commands and output, as well as how you installed Postgres.

**Comment by ankane** [comment]
Thanks, can you paste the output of:

```sh
which pg_config
pg_config
```

**Comment by Lesley217** [comment]
which pg_config
/usr/local/bin/pg_config

pg_config
BINDIR = /usr/local/Cellar/postgresql@14/14.11_1/bin
DOCDIR = /usr/local/Cellar/postgresql@14/14.11_1/share/doc
HTMLDIR = /usr/local/Cellar/postgresql@14/14.11_1/share/doc
INCLUDEDIR = /usr/local/include/postgresql@14
PKGINCLUDEDIR = /usr/local/include/postgresql@14
INCLUDEDIR-SERVER = /usr/local/include/postgresql@14/server
LIBDIR = /usr/local/lib/postgresql@14
PKGLIBDIR = /usr/local/lib/postgresql@14
LOCALEDIR = /usr/local/Cellar/postgresql@14/14.11_1/share/locale
MANDIR = /usr/local/Cellar/postgresql@14/14.11_1/share/man
SHAREDIR = /usr/local/share/postgresql@14
SYSCONFDIR = /usr/local/Cellar/postgresql@14/14.11_1/etc
PGXS = /usr/local/lib/postgresql@14/pgxs/src/makefiles/pgxs.mk
CONFIGURE =  '--disable-debug' '--prefix=/usr/local/Cellar/postgresql@14/14.11_1' '--datadir=/usr/local/share/postgresql@14' '--libdir=/usr/local/lib/postgresql@14' '--includedir=/usr/local/include/postgresql@14' '--enable-thread-safety' '--with-gssapi' '--with-icu' '--with-ldap' '--with-libxml' '--with-libxslt' '--with-lz4' '--with-openssl' '--with-pam' '--with-perl' '--with-uuid=e2fs' '--with-extra-version= (Homebrew)' '--with-bonjour' '--with-tcl' 'PG_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk' 'CC=clang' 'LDFLAGS=-L/usr/local/opt/openssl@3/lib -L/usr/local/opt/readline/lib' 'CPPFLAGS=-I/usr/local/opt/openssl@3/include -I/usr/local/opt/readline/include' 'CXX=clang++' 'PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/openssl@3/lib/pkgconfig:/usr/local/opt/krb5/lib/pkgconfig:/usr/local/opt/lz4/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/14'
CC = clang
CPPFLAGS = -I/usr/local/Cellar/icu4c/74.2/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/usr/local/opt/openssl@3/include -I/usr/local/opt/readline/include -I/usr/local/Cellar/lz4/1.9.4/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-deprecated-non-prototype -O2
CFLAGS_SL = 
LDFLAGS = -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -L/usr/local/opt/openssl@3/lib -L/usr/local/opt/readline/lib -L/usr/local/Cellar/lz4/1.9.4/lib -Wl,-dead_strip_dylibs
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -llz4 -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lm 
VERSION = PostgreSQL 14.11 (Homebrew)

**Comment by ankane** [comment]
Hmm, still don't see the issue. Is the `PG_CONFIG` environment variable set?

```sh
echo $PG_CONFIG
```

Does it work with:

```sh
make PG_CONFIG=/usr/local/bin/pg_config
```

**Comment by Lesley217** [comment]
Thanks a lot for your patience.  I tried running both.
echo $PG_CONFIG

make PG_CONFIG = /usr/local/bin/pg_config
make: *** empty variable name.  Stop.

**Comment by Lesley217** [comment]
Thanks a lot ! I reinstalled x-code again and download pgvector with Homebrew. It works afterwards.
