### ISSUE TITLE
Increase VECTOR_MAX_DIM 

### ISSUE THREAD

**Issue by 64bit** [pgvector/pgvector#52]
Hello, Great project! Just what I was looking for a vector database in Rust. 

I was working on an OpenAI embedding project  to use pgvector with [async-openai](https://github.com/64bit/async-openai). However I immediately ran into VECTOR_MAX_DIM limit of 1024 on first insert. The output of latest Embedding model on OpenAI is of dimension [1536](https://beta.openai.com/docs/guides/embeddings/second-generation-models). 

Having VECTOR_MAX_DIM doubled to 2048 will solve this particular use case, so wondering if increasing is someting that would align with the goals of the pgvector project?

Thank you

**Comment by ankane** [comment]
Hey @64bit, you should be able to increase it to 1536 in `src/vector.h` without increasing the block size for Postgres (2048 won't fit a a single page).

I'm hoping to increase it in the 0.4.0 release (but want to make sure compression and out-of-line storage are supported first).

**Comment by gregnr** [comment]
Hey @ankane, thanks for the comment and great work on this extension. I have the same use case as @64bit, specifically requiring the 1536 dimension limit for OpenAI's Embedding model.

You mentioned that you have concerns with compression and out-of-line storage. I have a basic understanding of these, but am hoping to clarify. Are you concerned that TOAST may not apply to `pgvector` since it is a third-party data type vs. native? Would this apply only to sizes greater than PG's block size (eg. 2048), or could this happen with 1536?

Thanks!

**Comment by 64bit** [comment]
Thank you @ankane - I do not have understanding of internals so its best for me to wait for 0.4.0.

**Comment by ankane** [comment]
@gregnr The `vector` type uses `PLAIN` storage in the current release. It'll use `EXTENDED` in 0.4.0 (the storage format is already compatible with it - just needs to be enabled). https://www.postgresql.org/docs/current/storage-toast.html

@64bit I bumped the limit to 16000 dimensions for vectors and 2000 for indexes on master (just remove `--branch v0.3.2` from the installation instructions). Need to do some more testing around memory management, but it should be fine to use in development.

**Comment by gregnr** [comment]
@ankane Thank you for your response and clarification around the `EXTENDED` type. Can't believe how quick your updates are.

Thanks again for your work on this extension. I am eager for 0.4.0!

**Comment by ankane** [comment]
0.4.0 is out with updated limits 🎉

**Comment by 64bit** [comment]
@ankane thank you. What a pleasant surprise! I echo @gregnr sentiments - can't belive how quick the update is. I hope to try this soon.
