### ISSUE TITLE
Sometimes tap-tests fail

### ISSUE THREAD

**Issue by kav23alex** [pgvector/pgvector#535]
Sometimes tests fail. I slightly modified the 012_hnsw_build_recall.pl test to reduce the number of runs to get an error.
```
diff --git a/test/t/012_hnsw_build_recall.pl b/test/t/012_hnsw_build_recall.pl
index 1298009..ff437a3 100644
--- a/test/t/012_hnsw_build_recall.pl
+++ b/test/t/012_hnsw_build_recall.pl
@@ -54,9 +54,10 @@ $node->start;
 $node->safe_psql("postgres", "CREATE EXTENSION vector;");
 $node->safe_psql("postgres", "CREATE TABLE tst (i int4, v vector(3));");
 $node->safe_psql("postgres",
-       "INSERT INTO tst SELECT i, ARRAY[random(), random(), random()] FROM generate_series(1, 10000) i;"
+       "SELECT setseed(-0.536); INSERT INTO tst SELECT i, ARRAY[random(), random(), random()] FROM generate_series(1, 10000) i;"
 );

+srand(3579673785);
 # Generate queries
 for (1 .. 20)
 {
```
reproduce:
```
for i in `seq 10`; do make PROVE_TESTS=test/t/012_hnsw_build_recall.pl USE_PGXS=1 PG_CONFIG=/REL_16_STABLE/bin/pg_config prove_installcheck || break; done

result:
test/t/012_hnsw_build_recall.pl .. 15/?
#   Failed test '<#>'
#   at test/t/012_hnsw_build_recall.pl line 45.
#     '0.79'
#         >=
#     '0.8'
test/t/012_hnsw_build_recall.pl .. 21/?
```

Maybe I'm wrong, but tests built on random numbers can sometimes fail.
Perhaps it is worth initializing with a given initial seed before generating data in all tap-tests?

for example:
from SQL: SELECT setseed(0.5);
from perl: srand(1000);

**Comment by ankane** [comment]
Hi @kav23alex, I'd like to keep the randomness since I think it does a better job of uncovering issues, but a few strategies to reduce the flakiness would be:

1. Lower the thresholds
2. Test more queries (to reduce variance)
3. Use a different distribution (since vectors of uniform random numbers will all have a similar inner product)

I've updated that test and similar tests in the commit above and a follow-up commit, and will continue to make adjustments as needed.
