### ISSUE TITLE
Index tweaking for getting some specific recall

### ISSUE THREAD

**Issue by Giorgi** [pgvector/pgvector#606]
Hello,

When creating an index (HNSW or IVFFlat) how do I know what values to use for the index parameters to get the desired recall? For example, let's say I want to have a recall of 0.97 with HNSW. How do I calculate what values to use for `m` and `ef_construction`?

**Comment by ankane** [comment]
Hi @Giorgi, check out https://github.com/pgvector/pgvector/issues/543#issuecomment-2098860327.

**Comment by TopCoder2K** [comment]
@ankane, but what if I don't obtain the desired Recall even with `m=64, ef_construction=512` (I have 88.5% but I'd like to have 95%+)? Moreover, `ef_construction` can't exceed 1000, but even if I could break the limits, increasing `m` and `ef_construction` wouldn't add much (with `m=32, ef_construction=256` I had 84%). And building the HNSW index with `m=64, ef_construction=512` already takes ≈8 hours.

Probably, my case is specific, since I measure Recall on TOP-1000 and I have a significant amount of duplicate vectors (for example, for one of my partitions, the hugest group of duplicate vectors reaches 1.5% of the total number of vectors and around 20% of vectors belong to some duplicate group).
