### ISSUE TITLE
Cant use DISTINCT ON

### ISSUE THREAD

**Issue by mfandre** [pgvector/pgvector#641]
Always receive the follow error: _SQL Error [42P10]: ERROR: SELECT DISTINCT ON expressions must match initial ORDER BY expressions_

```
SELECT distinct on (embedding, path) path
FROM chunks 
ORDER BY embedding <=> '[0.00581426,-0.0013586936,0.009351607,-0.0007560063,...]',path
LIMIT 3
```

<img width="874" alt="image" src="https://github.com/user-attachments/assets/fcd3c8ae-a42f-4603-8108-561a1098b1b7">

**Comment by ankane** [comment]
Hi @mfandre, this error isn't specific to pgvector. Please use other resources for help.

https://www.postgresql.org/docs/current/sql-select.html#SQL-DISTINCT

**Comment by mfandre** [comment]
@ankane I disagree, it worked perfectly when it used without embbeding order by.  The problem is something relationed in how oder by embbeding is constructed behind de scenes.

**Comment by jkatz** [comment]
@mfandre What you described above is a different type of query. With your first query:

```sql
SELECT DISTINCT ON (embedding, path) path
FROM chunks
ORDER BY embedding <=> '[...]'
LIMIT 3
```

your `ORDER BY` clause is calculating the distance between `embedding` and a query vector, whereas your projection (`DISTINCT ON`) is using just the value of `embedding`.

If you want to use `DISTINCT ON` using the distance, you would write it with something like this (untested):

```sql
SELECT DISTINCT ON (distance, path)
  embedding <=> '[...]' AS distance, path
FROM chunks
ORDER BY distance
LIMIT 3;
```

though (again untested in this case) I don't see the difference between that and using `DISTINCT`.

For the second query, the reason it worked is because you don't have to account for ordering. As it says in the docs that @ankane referenced:

> ...[DISTINCT ON] keeps only the first row of each set of rows where the given expressions evaluate to equal.

so because order matters, the values in `DISTINCT ON` must match the same values provided in order in the `ORDER BY` clause.

**Comment by mfandre** [comment]
Makes sense, Thx por explanation!
