### ISSUE TITLE
OOM  errors - during insertion and HNSW l1 INDEX builds  on  version "0.7.2"

### ISSUE THREAD

**Issue by aiseei** [pgvector/pgvector#643]
Hi, 

Think pgvector isnt the issue nevertheless any leads would be useful. 

Setup that works:

##Ubuntu 14.9-1.pgdg20.04+1 ## on 8 cpu, 32g RAM VM.

"checkpoint_completion_target"	"0.9"	
"effective_cache_size"	"3145728"	"8kB"
"effective_io_concurrency"	"200"	
"huge_pages"	"try"	
"maintenance_work_mem"	"2097152"	"kB"
"max_connections"	"200"	
"max_parallel_workers"	"8"	
"max_parallel_workers_per_gather"	"4"	
"max_wal_size"	"8192"	"MB"
"max_worker_processes"	"8"	
"min_wal_size"	"2048"	"MB"
"random_page_cost"	"1.1"	
"shared_buffers"	"1048576"	"8kB"
"temp_buffers"	"1024"	"8kB"
"wal_buffers"	"2048"	"8kB"
"work_mem"	"10485"	"kB"

-------------------------------------
Setup that errors WITH ===> mmap(8812232704) with MAP_HUGETLB failed, huge pages disabled: Cannot allocate memory

##Ubuntu 14.13-1.pgdg22.04+1## on 24CPU , 220gb RAM + A100 80GB VM##

"checkpoint_completion_target"	"0.9"	
"effective_cache_size"	"10813440"	"8kB"
"effective_io_concurrency"	"200"	
"huge_pages"	"try"	
"maintenance_work_mem"	"2097152"	"kB"
"max_connections"	"200"	
"max_parallel_workers"	"12"	
"max_parallel_workers_per_gather"	"4"	
"max_wal_size"	"8192"	"MB"
"max_worker_processes"	"12"	
"min_wal_size"	"2048"	"MB"
"random_page_cost"	"1.1"	
"shared_buffers"	"3604480"	"8kB"
"temp_buffers"	"1024"	"8kB"
"wal_buffers"	"2048"	"8kB"
"work_mem"	"36044"	"kB"

----------------------------

Tried all manner of tweaks to pg config + also tried reducing the chunks size from 8096 (which works on the smaller setup) to 4096.  Nothing works and the DB shuts down when the only process is vector creations / insertions. 

Has anyone faced something similar ? 

@ankane @jkatz   any guidance would highly appreciated. 

Thanks.
Aiseei

**Comment by jkatz** [comment]
It's tough to provide guidance without knowing what query you're running where you see the OOM, if you're running this in a container or a standard process, what other processes are running on the system, and if there are any other memory constraints in place.

**Comment by ankane** [comment]
Hi @aiseei, it seems like something is limiting the memory that's available for Postgres. I'd confirm you don't have any [memory constraints](https://docs.docker.com/engine/containers/resource_constraints/) set on the container (or anywhere else in the system).

Going to close this out since it doesn't seem like an issue with pgvector, but @jkatz may have additional ideas.

**Comment by jkatz** [comment]
Borrowing a bit from another issue, it's very similar to what Andrew suggests. Because your HNSW index build is exceeding the available memory to build the index, which is likely governed by your container (cgroup) limits, the OOM killer is taking out the process, even If you have more resources on the machine. If the memory in your container exceeds the threshold cgroup threshold, the OOM killer kills the process putting on the most memory pressure (Joe Conway has an [excellent blog on this topic](https://www.crunchydata.com/blog/deep-postgresql-thoughts-the-linux-assassin)).
