### ISSUE TITLE
HNSW + Filter inconsistent result issue (based on HNSW index used vs unused)

### ISSUE THREAD

**Issue by vinodhbalasubramanian** [pgvector/pgvector#671]
Postgres gives inconsistent result count when it uses the HNSW index vs index not being used.

I am using PGVector HNSW USING hnsw (embedding vector_cosine_ops) WITH (m='16', ef_construction='32');
IFacing an issue with the below sample query 

WITH filtered_opportunities AS (SELECT sf.notice_id FROM opportunity_filter sf 
WHERE 
sf.full_parent_path_name IN ('ABC SERVICE')
//and has_related_award=true // line 2
) 
SELECT sv.notice_id FROM semantic_vector sv  JOIN filtered_opportunities fo ON fo.notice_id = sv.notice_id 
ORDER BY sv.embedding <=> cast('[-0.5078125]’) limit 200

From the above query, It gives me a result count of 30 by having one filter condition, if I add another AND condition (uncomment line 2) it is giving me 200 records (ideally adding more where condition should reduce the resultset). 

The difference in above is, with the first query, it uses HNSW index, so postgres fetches 1000 records from vector table & then apply filter on top of it which reduces the resultset, in the second query postgres doesn't uses HNSW index, so it fetches more records while applying the filter at same time. This is a major issue in our application, where the filters behaves differently based on HNSW index used/not used.

Is this is a Postgres bug? any way to solve this?

**Comment by vinodhbalasubramanian** [comment]
@jkatz Thanks for your reply.
1. Is there a development on going to fix this bug? any approximate timeframe when we could expect this fix?
2. Do you mean to use GIN index for embedding field instead of HNSW index? Currently, I am already using the HNSW index for embedding in vector table and the B-tree index for full_parent_path_name & has_related_award. 
3. currently we are using hnsw.ef_search (m='16', ef_construction='64'), if we increase this more than 64, won't that lead for performance issue? I hope you mean to increase this to get more records & avoid loosing more records during filter isn't it?

**Comment by jkatz** [comment]
@vinodhbalasubramanian This isn't a bug, but an active area of research. Please see #244.

If your data is already B-tree indexed, and you're using those columns in the filters, I would suggest using that instead of a HNSW index to see if you can achieve your query latency target. The benefit of that is you'll also have 100% recall.

**Comment by vinodhbalasubramanian** [comment]
@jkatz  Could you please explain why this is not considered as a bug? I run my query with one filter, it gives me less records & when I add another filter, it gives me more records, as a developer it is not a code logic bug, this discrepancy occurs based on Postgres query plan usage (HNSW index vs filter index), we could not able to control this query plan.
Also your suggestion to use B-tree index & avoid HNSW index, it is not possible because:
1. Whenever we don't apply the filter conditions then we need to use HNSW index for faster retrieval
2. In some conditions Postgres doesn't use the B-tree index Ex: if the filter parameter has a condition that pulls heavy data (Ex: amount>1 and amount <100000), in this case Postgres doesn't use any of the index even though amount parameter is B-Tree index.

**Comment by jkatz** [comment]
@vinodhbalasubramanian As mentioned previously, this has to do with how the HNSW index is searching and returning rows. The search occurs on vector similarity, and it doesn't account for the filters. The filters are applied after the index is scanned. You can increase the number of results returned from the index by increasing `hnsw.ef_search`.

However, as stated (and discussed in #244), this is in general an area of active research around considering filters as part of a vector similarity search. If you have examples of the types of filters that you're running on your similarity search queries, along with overall dataset size and how much data you expect to be returned by a filter, that would help with determining how we want to proceed with supporting in-index filtering (aka "prefiltering").

> In some conditions Postgres doesn't use the B-tree index Ex: if the filter parameter has a condition that pulls heavy data (Ex: amount>1 and amount <100000), in this case Postgres doesn't use any of the B-tree indexes even though amount parameter is B-Tree index.

This may be because the PostgreSQL query planner believes a sequential scan is faster than an index scan for this case (and it very may well be, without knowing anything about your data).

**Comment by vinodhbalasubramanian** [comment]
@jkatz Already our hnsw.ef_search is set to 1000 I hope it is maximum in PGVector. If we apply on top of this 1000 records then we are loosing records count significantly. Any approax timeline when we are trying to implement this HNSW fix to consider the filters?

**Comment by ankane** [comment]
Hi @vinodhbalasubramanian, there isn't a timeline right now.

**Comment by ankane** [comment]
Spoke too soon, see #677 for the current plan.

**Comment by vinodhbalasubramanian** [comment]
@ankane Thanks for your response. reg. #677 "Filtering improvements-iterative index scans for HNSW".   Will this change scans the embeddings along with the filters? will this change resolves our issue? i.e. HNSW scans along with applying filters at the same time?

**Comment by ankane** [comment]
See https://github.com/pgvector/pgvector/issues/259#issuecomment-2362500744 for more info

**Comment by vinodhbalasubramanian** [comment]
@ankane Thanks, I hope this "iterative index scans" will return us more records with filters. We will wait for this October release and see.
