### ISSUE TITLE
Iterative index scans

### ISSUE THREAD

**Issue by ankane** [pgvector/pgvector#678]
Hi all, I wanted to share some work on iterative index scans to get feedback.

- [hnsw-streaming branch](https://github.com/pgvector/pgvector/compare/hnsw-streaming)
- [ivfflat-streaming branch](https://github.com/pgvector/pgvector/compare/ivfflat-streaming)

You can enable this functionality (naming TDB) with:

```sql
SET hnsw.streaming = on;
SET ivfflat.streaming = on;
```

For HNSW, it keeps track of discarded candidates at layer 0. When more tuples are needed, it calls `HnswSearchLayer` /  Algorithm 2 with the nearest discarded candidates as entry points (in batches of `ef_search`). The scan terminates when enough tuples are found, `hnsw.ef_stream` elements are visited, or `work_mem` is exceeded.

For IVFFlat, it scans the next closest lists in groups of `ivfflat.probes`, up to `ivfflat.max_probes`.

---

One issue I'm having trouble addressing is how to terminate scans for queries with distance filters. In the query below, if only 9 records are within the distance, it'll continue scanning the index. I've tried using `xs_orderbyvals` on `IndexScanDesc`, but it doesn't seem to help.

```sql
SELECT * FROM items WHERE embedding <-> $1 < 0.1 ORDER BY embedding <-> $1 LIMIT 10;
```

**Comment by jkatz** [comment]
@ankane Isn't that part of the scan key? (`IndexScanDesc->keyData`; type `ScanKeyData`); Maybe checking if there's an explicitly vector distance computation within the scan keys and set that as one of the flags as part of the HNSW/IVFFlat scan so we don't need to continuously recheck.

**Comment by ankane** [comment]
`scan->numberOfKeys` is always zero in my testing.

**Comment by jkatz** [comment]
@ankane I'm unlikely to dive into this tonight, but from a quick [doc read on index scanning](https://www.postgresql.org/docs/current/index-scanning.html) the scan keys should be available in `amrescan`. I see that `hnswrescan` is checking that, so my very quick thought is that the optimizer may not be pushing the scan keys down to this particular path. Curious what `nkeys` has?

**Comment by ankane** [comment]
`nkeys` is zero as well.

**Comment by VladlenPopolitov** [comment]
@ankane Hi! I tested performance, it is good for post-search filter. I did tests and found, that search crashed after truncate table. Need to fix streaming search from empty index.

**Comment by VladlenPopolitov** [comment]
@ankane  I added pull request [679](https://github.com/pgvector/pgvector/pull/679) with test, that fails now after TRUNCATE table. It can be used in the future to check updates in the code.

**Comment by ankane** [comment]
Thanks @VladlenPopolitov, fixed in b2fa6252552ad31de320c12c2fedc5353dcdc993.

**Comment by hlinnaka** [comment]
Nice to see some action on this!

I had a look at the [hnsw-streaming](https://github.com/pgvector/pgvector/compare/hnsw-streaming) branch, thinking how it compares with the previous work I did at https://github.com/hlinnaka/pgvector/tree/hnsw_iterator (discussed in PR #282),  and #524. If I understand correctly, hnsw-streaming and my "hnsw_iterator" implementation use the same approach: Instead of discarding items, put them in another heap, and take items back from that heap if more items are needed. The difference is that hnsw-streaming works in batches, while hnsw_iterator runs the algorithm continuously on every tuple.

At quick glance, I think PR #524 is more similar to hsnw-treamng, as it also works in batches.

It would be interesting to benchmark these. I like the continuous approach in hnsw_iterator, it feels more principled than working in batches, but it probably doesn't make much difference in practice.

For easier comparison, I rebased and squashed my hnsw_iterator branch on top of current 'master'. It doesn't handle the vacuum locking correctly, but that should be easy to fix. The code is structured so that it keeps the existing HnswSearchLayer code unmodified for the non-continuous case, and duplicates the logic. This makes it easier to compare, but the code could easily be deduplicated.

**Comment by VladlenPopolitov** [comment]
@hlinnaka PR #524 saves all visited tuples to priority queue (w queue) and continues the search (candidates queue). gettuple returns the best candidate from these 2 queues.
I did benchmark yesterday, all approaches shows relatively same performance, though hnsw-streaming is slightly better.
![benchmark3_995](https://github.com/user-attachments/assets/da099719-f968-42c2-95b7-114be70d2cb5)
![benchmark3_995](https://github.com/user-attachments/assets/b57daf2a-2bcb-4250-96d0-37e568afd0e0)

**Comment by jkatz** [comment]
@VladlenPopolitov thanks for the comparative tests! However, I don't think the MNIST dataset gives enough context, because it's such a small dataset, it's better for a quick check. If you're using ANN Benchmarks, can you run with a few more datasets, I'd recommend:

- dbpedia-openai-1000k-angular
- sift-128-euclidean
- gist-960-euclidean

For bonus points, lately I've been using [VectorDBBench](https://github.com/zilliztech/VectorDBBench) for heavier tests, as it supports concurrency testing. It includes a 5MM OpenAI-based dataset (1536-dim) and a 10MM Cohere-based datsets (768-dim). I'm likely going to do some deeper testing with those, but if you're able to at least run some quick tests with the ANN Benchmark compatible datasets listed above, that would be great.

**Comment by ankane** [comment]
@hlinnaka I think the main benefits to batching are:

1. Minimizing out of order elements (elements can only be out of order between batches)
2. Less code duplication
3. Possibly better performance with how vacuum locking is currently implemented

`batch_size` is currently `ef_search`, but it could be as small as 1.

**Comment by alanwli** [comment]
@ankane, just a couple thoughts off the top of my head:

1. You allude to this re: "Minimizing out of order elements", this would break SQL semantics of returning out-of-order items with ORDER BY ... LIMIT.
2. What is the impact on the long-tail cases - e.g. worse case scenario of reaching deeper in the index, but all tuples are just either not visible or doesn't pass the predicate filter. How deep will it reach?

**Comment by ankane** [comment]
Hi @alanwli,

1. Correct. We could filter out tuples that are closer than the last one returned to avoid this, but this could affect recall.
2. The scan will end when either: A. Enough tuples are returned B. `work_mem` is reached or C. `hnsw.ef_stream` is reached.

See the readme changes in the `hnsw-streaming` branch for more info.

**Comment by ankane** [comment]
Looking at SIFT 1M, a decent % of tuples can be discarded if strict ordering is implemented (with a filter selectivity of 0.01, usually 2-7%, but sometimes more than 10%).

**Comment by VladlenPopolitov** [comment]
> @VladlenPopolitov thanks for the comparative tests! However, I don't think the MNIST dataset gives enough context, because it's such a small dataset, it's better for a quick check. If you're using ANN Benchmarks, can you run with a few more datasets, I'd recommend:
> 
> * dbpedia-openai-1000k-angular
> * sift-128-euclidean
> * gist-960-euclidean
> 
> For bonus points, lately I've been using [VectorDBBench](https://github.com/zilliztech/VectorDBBench) for heavier tests, as it supports concurrency testing. It includes a 5MM OpenAI-based dataset (1536-dim) and a 10MM Cohere-based datsets (768-dim). I'm likely going to do some deeper testing with those, but if you're able to at least run some quick tests with the ANN Benchmark compatible datasets listed above, that would be great.

@jkatz it was not performance benchmark, it was quick functional test. It showed good functions of this branch for filtering search and found one bug, that already fixed.

**Comment by VladlenPopolitov** [comment]
> @ankane I'm unlikely to dive into this tonight, but from a quick [doc read on index scanning](https://www.postgresql.org/docs/current/index-scanning.html) the scan keys should be available in `amrescan`. I see that `hnswrescan` is checking that, so my very quick thought is that the optimizer may not be pushing the scan keys down to this particular path. Curious what `nkeys` has?
@jkatz 
nkeys is more than  zero if 1) index build with multiple columns or expressions 2) these columns or expressions are used in WHERE clause (and operator is described in class operator definition) - the number of these operators in WHERE equals to nkeys.  The first condition already is not true for pgvector, it is not defined as multicolumn index and cannot accept other columns in CREATE INDEX command.

**Comment by alanwli** [comment]
> Looking at SIFT 1M, a decent % of tuples can be discarded if strict ordering is implemented (with a filter selectivity of 0.01, usually 2-7%, but sometimes more than 10%).

IIUC, does this mean recall will be lower by 10% since this will be discarding nearer vectors?

@ankane, @jkatz - more generally, I was curious how you both & PG community are thinking about vector search vs. correct SQL semantics?

**Comment by jkatz** [comment]
@alanwli What's the incorrect semantic here? PostgreSQL has supported K-NN index searches with GiST for more than a decade.

**Comment by ankane** [comment]
The additional incorrect semantic is results may not be strictly ordered (which won't happen with GiST).

I'd like to minimize these, as it's not intuitive for users, but think the trade-off is probably worth it here.

(if we strictly adhered to SQL semantics, there'd be no approximate indexes)

**Comment by jkatz** [comment]
> The additional incorrect semantic is results may not be strictly ordered (which won't happen with GiST).

(Actually, that's not necessarily true 😄 GiST can support lossy index structures and can require an additional reranking, but it has the reranking mechanism built-in, which does allow for the reordering. But...I do wonder what happens with a higher dimensional `cube` vector in a GiST index)

**Comment by ankane** [comment]
This is true from the user's perspective :) It'd be great if we could do something similar, but the recheck code in Postgres requires strict ordering.

**Comment by ankane** [comment]
Some data on how batch size and selectivity affect out of order results with SIFT 1M (default parameters, limit 20).

batch_size | sel 0.1 | sel 0.01
--- | --- | ---
1 | 14.3% | 2.8%
10 | 9.4% | 2.6%
40 | 5.5% | 2.3%
100 | 1.4% | 2.0%
200 | 0% | 1.5%
1000 | 0% | 0.3%

(this shows final out of order results, which is lower than % of out of order results during the scan, since many out of order results will not pass the filter condition)

**Comment by jkatz** [comment]
> This is true from the user's perspective :) It'd be great if we could do something similar, but the recheck code in Postgres requires strict ordering.

I recall (no pun intended) that you could actually get it to return results in an incorrect order, but only if you didn't recheck. That said, that's on the index implementor interfacing with GiST.

That said, I know that approximate search with vectors has been a topic of discussion for the SQL committee - I don't know if that will end up leading to additional SQL syntax around approximate searches, but that is one way that the inherent semantics could change. Until then, I agree with Andrew's original point.

**Comment by alanwli** [comment]
> @alanwli What's the incorrect semantic here? PostgreSQL has supported K-NN index searches with GiST for more than a decade.

To clarify, I'm referring the semantics of the current discussion - @ankane's branch has the following example query where the outer ORDER BY would be needed because the inner ORDER BY LIMIT may return out of order results, which does not follow SQL semantics.

`WITH approx_order AS MATERIALIZED (
    SELECT *, embedding <-> '[1,2,3]' AS distance FROM items WHERE ... ORDER BY distance LIMIT 5
) SELECT * FROM approx_order ORDER BY distance;`

**Comment by ankane** [comment]
Some benchmarking results from the [`arxiv` dataset](https://github.com/qdrant/ann-filtering-benchmark-datasets) (2.1M rows, 384 dimensions, first 100 queries, default build parameters, 6GB shared buffers)

Branch | Time | Recall
--- | --- | ---
hnsw-filtering | 108 sec | 95.8 
hnsw_iterator* | 167 sec | 95.9
relaxed | 221 sec | 95.5 

It'd be great to see benchmarks from others as well.

---

\* with a patch to fix recall

```diff
diff --git a/src/hnswutils.c b/src/hnswutils.c
index d6ed0b56..6b25eae8 100644
--- a/src/hnswutils.c
+++ b/src/hnswutils.c
@@ -966,7 +966,7 @@ LoadCandidates(char *base, IndexScanDesc scan, int ef)
 
 				/* Avoid any allocations if not adding */
 				eElement = NULL;
-				HnswLoadElementImpl(blkno, offno, &eDistance, &so->q, index, so->procinfo, so->collation, false, alwaysAdd ? NULL : &f->distance, &eElement);
+				HnswLoadElementImpl(blkno, offno, &eDistance, &so->q, index, so->procinfo, so->collation, false, NULL, &eElement);
 
 				if (eElement == NULL)
 					continue;
```

**Comment by jkatz** [comment]
@ankane I'm currently running a test [VectorDBBEnch](https://github.com/zilliztech/VectorDBBench) using the 5MM 1536d (OpenAI) dataset, I can post results when that's done. I'm currently drilling into a `k=100` case.

**Comment by ankane** [comment]
Great, just ran the benchmark above with strict ordering enabled ([branch](https://github.com/pgvector/pgvector/compare/hnsw-streaming...hnsw-streaming-strict)). It drops the recall from 95.8 to 91.8.

**Comment by ankane** [comment]
One idea is to allow users to select the mode:

```tsql
SET hnsw.iterative_search = off; -- default for 0.8.0
SET hnsw.iterative_search = on;  -- strict, default for future version
SET hnsw.iterative_search = relaxed;
```

However, I think the distance filter issue mentioned in the first post may make it unfeasible to have either mode of streaming as the default, as users currently need to change how they write queries to avoid it.

**Comment by jkatz** [comment]
Here are results from using the [VectorDBBench](https://github.com/zilliztech/VectorDBBench) utility with Case 11 (`Performance1536D5M`) - 5MM OpenAI 1536d vectors. This is just a test with the flat vectors, no quantization (that is planned for a follow-up).

Here are the notable settings from the environment:

## Server
- r7gd.16xlarge (64 vCPU, 512GiB RAM)
- DB stored to NVMe, but entire workload is in memory
- PostgreSQL 16.4, Ubuntu 22.04
- Configuration:
  - `shared_buffers`: `128GB`
  - `work_mem`: `64MB`
  - `effective_cache_size`: `256GB`
  - (as we're only showing query performance, redacting other parameters)

## pgvector
- Index type: HNSW (`vector_cosine_ops`)
  - `m`: `16`
  - `ef_construction`: `256`
  - `k`: `100` - **this is purposely chosen to see how pgvector behaviors with a larger `k` - I'm also testing the "traditional" `k=10`.

## Results

| version | ef_search | recall | QPS (singe client) | QPS (max) | single client p99 (ms) | Max QPS p99 (ms) |
|---------|-----------|----------|-------------------|-----------|------------------------|------------------|
| 0.7.4   | 80        | 0.783    | 267               | 10,626    | 11.8                   | 9.7              |
| 0.8.0 (1a1221f) | 80 | 0.951    | 178               | 6,840     | 17.0                   | 13.8             |
| 0.7.4   | 100       | 0.920    | 228               | 9,023     | 13.4                   | 11.0             |
| 0.8.0 (1a1221f) | 100 | 0.921    | 257               | 10,378    | 12.7                   | 9.2              |
| 0.7.4   | 120       | 0.934    | 217               | 8,273     | 14.6                   | 11.2             |
| 0.8.0 (1a1221f) | 120 | 0.934    | 222               | 8,668     | 13.8                   | 10.9             |
| 0.7.4   | 155       | 0.950    | 168               | 6,668     | 16.5                   | 14.0             |
| 0.8.0 (1a1221f) | 155 | 0.950    | 181               | 6,983     | 16.5                   | 13.5             |
| 0.7.4   | 180       | 0.959    | 145               | 5,569     | 19.0                   | 17.9             |
| 0.8.0 (1a1221f) | 180 | 0.958    | 167               | 6,540     | 18.5                   | 14.6             |
| 0.7.4   | 240       | 0.970    | 114               | 4,398     | 23.1                   | 21.9             |
| 0.8.0 (1a1221f) | 240 | 0.970    | 131               | 4,920     | 22.8                   | 19.6             |
| 0.7.4   | 350       | 0.981    | 85                | 3,254     | 29.6                   | 29.1             |
| 0.8.0 (1a1221f) | 350 | 0.981    | 92                | 3,528     | 29.4                   | 27.7             |
| 0.7.4   | 600       | 0.990    | 57                | 2,092     | 44.2                   | 46.6             |
| 0.8.0 (1a1221f) | 600 | 0.990    | 59                | 2,233     | 43.4                   | 44.4             |


## Results

With streaming mode, there's an interesting recall bump in `1a1221f` when `hnsw.ef_search` < `LIMIT` - per an offlist discussion with Andrew, this is due to the iterative scan working to satisfy the limit. Cool! That said, it comes with a performance impact, but that's likely still better behavior than "not returning enough results" (though that tends to be noticed more when a filter / `WHERE` clause is involved).

Once `hnsw.ef_search` >= `LIMIT`, we see the recall realign, but the streaming branch is showing nontrivial gains in performance (10-15%).

**Comment by ankane** [comment]
Awesome, thanks for sharing! The performance improvements likely come from work done before this branch (reducing memory usage for HNSW index scans).

**Comment by jkatz** [comment]
Similar to https://github.com/pgvector/pgvector/issues/678#issuecomment-2381458610, but with `k=10`:

| version | ef_search | recall | QPS (singe client) | QPS (max) | single client p99 (ms) | Max QPS p99 (ms) |
|---------|-----------|--------|-------------------|-----------|------------------------|------------------|
| 0.7.4   | 20        | 0.874  | 648               | 27,608    | 5.5                    | 3.8              |
| 0.8.0 (1a1221f) | 20 | 0.870  | 732               | 32,810    | 5.3                    | 3.4              |
| 0.7.4   | 40        | 0.934  | 473               | 19,538    | 7.0                    | 5.3              |
| 0.8.0 (1a1221f) | 40 | 0.928  | 503               | 22,235    | 6.9                    | 4.7              |
| 0.7.4   | 60        | 0.956  | 351               | 14,554    | 9.0                    | 6.8              |
| 0.8.0 (1a1221f) | 60 | 0.953  | 387               | 16,839    | 9.0                    | 5.9              |
| 0.7.4   | 80        | 0.968  | 273               | 10,961    | 11.3                   | 9.5              |
| 0.8.0 (1a1221f) | 80 | 0.965  | 319               | 13,410    | 10.9                   | 7.4              |
| 0.7.4   | 220       | 0.989  | 26                | 4,880     | 21.0                   | 19.9             |
| 0.8.0 (1a1221f) | 220 | 0.990 | 143               | 5,506     | 20.4                   | 17.5             |

I'm now starting tests with quantization to `halfvec`. Following that will be binary quantization.

**Comment by ankane** [comment]
Iterative search has a much lower impact on recall for IVFFlat (which makes sense).

Same dataset as https://github.com/pgvector/pgvector/issues/678#issuecomment-2380359173 with 1500 lists:

Probes | Recall (non-iter) | Recall (relaxed)
--- | --- | ---
1 | 46.9 | 55.5
40 | 75.6 | 78
100 | 81.5 | 83.3
200 | 86.6 | 87.4

**Comment by ankane** [comment]
Also, for HNSW, I think it'd be good to spill the discarded candidates to disk once `work_mem` is exceeded (so search can keep going). I spent some time trying to figure out the best way to do this today, but it may need to wait for a future release.

**Comment by jkatz** [comment]
It turned out I didn't enable streaming correctly on the above tests, but that's OK because streaming wouldn't have taken effect; I reran a few and had very similar results. So as mentioned somewhere, this is due to all the other performance and memory improvements targeted for v0.8 (thanks @ankane!)

That said, I did run some tests that did leverage streaming today. Specifically, I used the dataset in here https://github.com/pgvector/pgvector/issues/678#issuecomment-2381458610 along with VectorDBBench to test the impact of streaming on the following query:

```sql
SELECT i.id
FROM (
    SELECT id, embedding <=> $2 AS distance
    FROM table_name
    ORDER BY binary_quantize(embedding)::bit(1536) <~> binary_quantize($2)
    LIMIT $3) i
ORDER BY i.distance LIMIT $1"
```

where:

- `$1` - equivalent of `k`
- `$2` - equivalent of the query vector
- `$3` - I call this the "inner limit" but I would vary this to see the effects of streaming. Streaming takes effect when $3 > `hnsw.ef_search`

I tested the above query with a variety of different configurations for streaming mode, and am posting the most interesting results here. For this test with binary quantization (BQ), I wanted to see the behavior targeted a recall of 90% (+/- 0.005 in the BQ portions) and see the impact of iterative scans, attempting to find the ideal configuration. The results are below. I include the size of the index in the results. The configurations are the same as https://github.com/pgvector/pgvector/issues/678#issuecomment-2381458610, though I'll specifically call out the pgvector config:

### pgvector
- Index type: HNSW (vector_cosine_ops)
  - `m`: `16`
  - `ef_construction`: `256`
  - `k` (`$1`): 10

In the below results, `$3` is the value of `hnsw.ef_search` unless explicitly stated in the `inner limit` column:

Here's the Markdown table:

| version | config | ef_search | inner limit | recall | QPS (singe client) | QPS (max) | single client p99 (ms) | Max QPS p99 (ms) | Index size (GiB) |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 0.7.4 | flat | 40 | - | 0.934 | 473 | 19,538 | 7.0 | 5.3 | 38.15 |
| 0.8.0 (1a1221f) | flat | 40 | - | 0.928 | 503 | 22,235 | 6.9 | 4.7 | 38.15 |
| 0.7.4 | halfvec | 40 | - | 0.927 | 465 | 21,108 | 7.0 | 5.7 | 19.07 |
| 0.8.0 (8b9333d) | halfvec | 40 | - | 0.925 | 501 | 23,661 | 6.4 | 4.4 | 19.07 |
| 0.7.4 | bq-rerank | 80 | - | 0.901 | 326 | 15,017 | 7.8 | 12.5 | 2.34 |
| 0.8.0 (8b9333d) | bq-rerank | 80 | - | 0.899 | 328 | 16,321 | 8.5 | 8.4 | 2.34 |
| 0.8.0 (8b9333d) | bq-rerank | 10 | 80 | 0.895 | 295 | 14,633 | 8.9 | 9.3 | 2.34 |
| 0.8.0 (8b9333d) | bq-rerank | 40 | 80 | 0.898 | 299 | 14,841 | 9.0 | 9.3 | 2.34 |
| 0.8.0 (8b9333d) | bq-rerank | 60 | 70 | 0.901 | 232 | 11,169 | 11.0 | 12.3 | 2.34 |

## Analysis

Hooray for the performance bump in a heads up comparison without streaming :smile: In my other tests, I did see ~10% boost at equivalent recalls.

The streaming results are interesting -- particularly because I can set a low value for `hnsw.ef_search` and still get comparable (though lower) performance across the board at equivalent recall. I do think the better tests would be with filters, but this at least provides a notion that even for BQ for this dataset/embedding model, it makes more sense to tweak `hnsw.ef_search` to find your target recall at peak performance instead of leaving `hnsw.ef_search` to a low value and increasing the inner limit.

**Comment by ankane** [comment]
Iterative search has now been merged 🎉 Still deciding on GUC naming, but the names for now are:

```sql
SET hnsw.iterative_search = on; -- relaxed
SET hnsw.iterative_search = strict;
SET ivfflat.iterative_search = on; -- relaxed
```

(will leave this thread open until the release for additional discussion)

**Comment by ankane** [comment]
Hi all, the current plan is to release 0.8.0 next week.

Rather than default no limit for `hnsw.max_search_tuples`, I think it'll be more clear to default to 20,000 (which is right around where search will end with the default `work_mem`). I think it's better to make this the main parameter to control search depth for HNSW, as in the future, search could spill to disk and continue once `work_mem` is exceeded.

I'm also considering adding an `hnsw.search_mem_multiplier` option ([search-mem-multiplier branch](https://github.com/pgvector/pgvector/compare/search-mem-multiplier)) to make it easier for users to adjust `work_mem` just for HNSW searches (similar to [hash_mem_multiplier](https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-HASH-MEM-MULTIPLIER)).

Let me know if you have any thoughts.

**Comment by VladlenPopolitov** [comment]
@ankane vacuum test takes 500 secs (100 times with 5 sec sleeps), and vacuum.out file is empty, test will fail anyway (and will not run tap tests). Probably forgot after debug.

**Comment by ankane** [comment]
I'm not sure what you're referring to.

**Comment by VladlenPopolitov** [comment]
> I'm not sure what you're referring to.

Sorry, I looked not in master branch. Please ignore it.

**Comment by ankane** [comment]
Merged the `hnsw.search_mem_multiplier` option and added an [iterative search section](https://github.com/pgvector/pgvector?tab=readme-ov-file#iterative-search) to the readme.

**Comment by wahajali** [comment]
@jkatz I had one question regarding the benchmarking numbers you shared above -- is the VectorDBBenchmark running on the same instance as the DB or running on a separate VM?

**Comment by ankane** [comment]
0.8.0 is now released. Thanks everyone!

(@wahajali I'd recommend moving your question to #700)
