### ISSUE TITLE
Impact of Indexes on Query Result Sets

### ISSUE THREAD

**Issue by mmmaia** [pgvector/pgvector#77]
Thanks for this project! I I have been using it and have successfully integrated it with AI-related projects such as LangChain and ChatGPT plugins.

One thing that I noticed is the impact of indexes on the result. It's not my standard thinking that an index would change the result set of a query, so I'd like to confirm it and shed more light into the matter to other users.

**Comment by ankane** [comment]
Hey @mmmaia, thanks for the contributions to those projects!

There's a line in the readme about this now ("unlike typical indexes which only affect performance, you may see different results for queries after adding an approximate index"), but I think that section could be a lot better, so will try to update it.

Adding an index enables approximiate nearest neighbor search (since there's not an efficient way to index exact search with high dimensional data). Two very important things to keep in mind to avoid bad results / poor recall are:

1. Create the index *after* the table has some data (IVFFlat indexes uses clustering internally, and without actual data, the cluster centers are random)
2. The [number of lists](https://github.com/pgvector/pgvector#index-options) should be set based on the application (lower is better for recall, higher is better for speed) - you want to set this as low as your application allows

Hopefully that all makes sense. For instance, it'd probably be good to remove the index in https://github.com/openai/chatgpt-retrieval-plugin/pull/45 since it would be created without any data.

**Comment by mmmaia** [comment]
Thanks, @ankane! I can't believe I didn't see that in the readme.

The two points are exactly what I experience during my tests and was confusing to me. Thanks for clarifying.


> For instance, it'd probably be good to remove the index in https://github.com/openai/chatgpt-retrieval-plugin/pull/45 since it would be created without any data.

Yup. Will do!

I'm sharing my learnings [here](https://medium.com/@mauricio/optimizing-ivfflat-indexing-with-pgvector-in-postgresql-755d142e54f5), hopefully it's correct and helps someone as confused as me :)

**Comment by ankane** [comment]
Nice, thanks for sharing! fwiw, for brute force / exact search, no index is needed (trying to create a `gin` index with a vector op class should fail).

One more thing about performance (not sure if this applies to the retrieval plugin): If vectors are guaranteed to be normalized (like those from `text-embedding-ada-002`), inner product will be faster than cosine distance for exact search (for approximate search, pgvector normalizes the indexed values, so it won't make a difference).

Also, I'll probably add a warning / info message when creating an index with too little data.

**Comment by mmmaia** [comment]
Perfect! Thanks for all the details and your patience.

**Comment by ankane** [comment]
No problem. Let me know if any other questions come up, and thanks again for the contributions.

**Comment by bfan1256** [comment]
Does this imply that if there was an index created before data - then you would get different results for the SAME query every time?

We are facing an issue in which data for the same query (with an order by) is different every time.
