### ISSUE TITLE
Where can I see benchmark data?

### ISSUE THREAD

**Issue by zhangliang-zl** [pgvector/pgvector#82]
Where can I see benchmark data? I would like to know the approximate memory usage and search time of 100w data? Do you have relevant architecture design documents?

**Comment by mmmaia** [comment]
Qdrant has a [framework for benchmarking vector search engines ](https://github.com/qdrant/vector-db-benchmark). It would be great to add pgvector to it.

I opened [an issue](https://github.com/qdrant/vector-db-benchmark/issues/46) there but didn't have the time to work on a pull request.

**Comment by ankane** [comment]
@zhangliang-zl pgvector will be included this month's [ann-benchmarks](https://github.com/erikbern/ann-benchmarks), so that'll be the best place when it's available.

I just performed an initial run of `sift-128-euclidean` on an `r6i.large` instance with 4000 lists and 1, 2, 4, 10, 20, 40, 100 probes, and the results are plotted below.

![plot](https://user-images.githubusercontent.com/220358/231008664-660da6dc-a15a-4910-baae-cd39393eacfa.png)

For architecture / design, [this paper](https://dl.acm.org/doi/pdf/10.1145/3318464.3386131) provides of good overview of Postgres indexing and the IVFFlat index type, and pgvector has a similar page structure.

@mmmaia Thanks for sharing. Would be great if someone wants to add it.

**Comment by ankane** [comment]
`glove-100-angular` with same parameters.

![plot](https://user-images.githubusercontent.com/220358/231320713-581bc448-84c1-4a80-bf5a-e3a80b35d669.png)
